version: 1
name: "Create GitHub Repository"
steps:
  - name: "OpenTofu Init"
    run: "tofu init"
    shell: "bash"

  - name: "OpenTofu Plan"
    run: |
      TF_VAR_repo_name="$REPO_NAME" \
      TF_VAR_repo_description="$REPO_DESCRIPTION" \
      TF_VAR_visibility="$VISIBILITY" \
      TF_VAR_has_issues="$HAS_ISSUES" \
      TF_VAR_has_wiki="$HAS_WIKI" \
      TF_VAR_github_token="$GITHUB_TOKEN" \
      tofu plan -out=tfplan
    shell: "bash"

  - name: "OpenTofu Apply"
    run: "tofu apply -auto-approve tfplan"
    shell: "bash"
